# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

resources:
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracksroot:0
    options:
    volumes: /mnt:/mnt:rw
         
jobs:
- job: Build_OpenEmbedded
  container: smartracks-build
  timeoutInMinutes: 3600
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  
  steps:
  - checkout: self
    submodules: true
  - script: |
      echo "Hello World7"
      echo "--Here--"
      cd /mnt
      ls -1
