# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pr:
#  branches:
#    include:
 #   - '*'  # must quote since "*" is a YAML reserved character; we want a string

#schedules:
#- cron: "0 * * * *"
#  displayName: 'Daily build'
#  branches:
#    include:
#     - main
     
resources:
  repositories:
  - repository: rcu-service
    type: github
    name: NI-SmartRack/rcu-service
    endpoint: SmartRacks
  - repository: smartracks-manifest
    type: github
    name: ni/smartracks-manifest
    endpoint: SmartRacks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:0
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
- job: Build_OpenEmbedded
  container: smartracks-build
  timeoutInMinutes: 3600
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  
  steps:
  - checkout: self
    submodules: true
  - checkout: smartracks-manifest
  - script: |
      echo "--Here TCH 20--"
      ls -1
      repo init -u https://github.com/ni/smartracks-manifest.git -b main -m smartracks-manifest.xml
      #cp smartracks-manifest/smartracks-manifest.xml .repo/local_manifest.xml
      #cd ~/bin/repo/smartracks-manifest
      #git init
      #git add smartracks-manifest.xml
      #repo init -m smartracks-manifest.xml
      
      echo "--1--"
      ls -1
      repo sync
      echo "--2--"
      ls -1
      #cd ..
      . export
      echo "--3--"
      ls -1
      #bitbake smartrack-minimal-image
      #cd /mnt/nirvana/perforceExports/smartracks/testing123
      # mkdir -p build-$(Build.BuildNumber)
      #ls -1
