# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pr:
#  branches:
#    include:
 #   - '*'  # must quote since "*" is a YAML reserved character; we want a string

#schedules:
#- cron: "0 * * * *"
#  displayName: 'Daily build'
#  branches:
#    include:
#     - main
     
resources:
  repositories:
  #- repository: rcu-service
   # type: github
    #name: NI-SmartRack/rcu-service
    #endpoint: SmartRacks
  #- repository: smartracks-manifest
   # type: github
    #name: ni/smartracks-manifest
    #endpoint: SmartRacks
  - repository: HatsyRei-smartracks-manifest
    type: github
    name: HatsyRei/smartracks-manifest-private
    endpoint: SmartRacks
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracks-build:0
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
- job: Build_OpenEmbedded
  container: smartracks-build
  timeoutInMinutes: 3600
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  
  steps:
  - checkout: self
    submodules: true
  - checkout: HatsyRei-smartracks-manifest
  - script: |
      echo "--Here TCH 20--"
      ls -1
      #repo init -u https://github.com/HatsyRei/smartracks-manifest.git -b main -m smartracks-manifest.xml
      #repo init -u https://github.com/ni/smartracks-manifest.git -b main -m smartracks-manifest.xml
      cd smartracks-manifest-private
      echo "--1--"
      ls -1
      #repo init -m smartracks-manifest.xml
      #repo sync
      #. export
      #bitbake smartrack-minimal-image
      #cd /mnt/nirvana/perforceExports/smartracks/testing123
      #mkdir -p /mnt/nirvana/perforceExports/smartracks/testing123/build-$(Build.BuildNumber)
      #cp deploy/images/apalis-imx8x/toradexlinux.tng /mnt/nirvana/perforceExports/smartracks/testing123/build-$(Build.BuildNumber)
      #cp deploy/images/apalis-imx8x/Apalis-iMX8X_Reference-Minimal-Image-rt-Tezi_5.1.0-devel-20201222130932+build.0.tar /mnt/nirvana/perforceExports/smartracks/testing123/build-$(Build.BuildNumber)
      #ls -1
