# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

schedules:
- cron: "3 * * * *"
  displayName: 'Daily build'
  branches:
    include:
     - main
     
resources:
  containers:
  - container: smartracks-build
    image: rnd-builds.repos.natinst.com/smartracks/smartracksroot:0
    options:
    volumes:
    - /mnt:/mnt
         
jobs:
- job: Build_OpenEmbedded
  container: smartracks-build
  timeoutInMinutes: 3600
  pool:
    name: Drivers-NIBuildFarm-RFMIBUILD
    demands:
      - docker
      - Agent.OS -equals Linux
  
  steps:
  - checkout: self
    submodules: true
  - script: |
      echo "--Here TCH--"
      cd /mnt/nirvana/perforceExports/smartracks/testing123
      mkdir -p build-$(Build.BuildNumber)
      ls -1
